In [1]:
import numpy as np

a = np.arange(20).reshape(4,5)
print(a)
print(a.ndim)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
2


#数组的创建
1. np.array()
2. 传入参数是list

In [9]:
num_a = np.array([2,3,4])
print(num_a)

[2 3 4]


创建二维数组

In [10]:
num_b = np.array([(1,2,3),(4,5,6)])
print(num_b)

[[1 2 3]
 [4 5 6]]


创建特定的数组
1. np.zeros   创建一个全是0的数组
2. np.ones    创建一个完整的数组
3. np.empty   创建一个随机的数组

In [40]:
num_c = np.zeros((4,4))
num_c1 = np.ones((2,3,4),dtype = np.int16)
num_c2 = np.empty((2,3))
print(" num_c = %s \n\n num_c1 = %s \n\n num_c2 = %s"%(num_c,num_c1,num_c2))

 num_c = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

 num_c1 = [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] 

 num_c2 = [[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


In [35]:
from numpy import pi
print(np.linspace(0,1,10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


数组的基本操作
 1. 可以做运算

In [38]:
a = np.array([10,9,8,7])
b = np.arange(4)
c = a-b
d = a*b
print(" c = %s \n d = %s"%(c,d))

 c = [10  8  6  4] 
 d = [ 0  9 16 21]
